version: "3"
services:
  foods:
    build:
      context: ./foods
      dockerfile: Dockerfile
    ports:
      - 4002:4002
    networks:
      - mynetwork

  users:
    build:
      context: ./users
      dockerfile: Dockerfile
    ports:
      - 4001:4001
    networks:
      - mynetwork

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    depends_on:
      - foods
      - users
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

