version: "3"
services:

  auth-helper:
    build:
      context: ./auth-helper
      dockerfile: Dockerfile
    ports:
      - 9001:9001
    networks:
      - mynet

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - 9002:9002
    networks:
      - mynet   

  styleguide:
    build:
      context: ./styleguide
      dockerfile: Dockerfile
    ports:
      - 9003:9003
    networks:
      - mynet

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 9004:9004
    networks:
      - mynet

  food:
    build:
      context: ./food
      dockerfile: Dockerfile
    ports:
      - 9005:9005
    networks:
      - mynet

  root-config:
    build:
      context: ./root-config
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    depends_on:
      - api
      - auth
      - auth-helper
      - food
      - styleguide
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
